# Generated by Django 2.2.16 on 2022-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20221112_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
